# https://www.home-assistant.io/integrations/default_config/
#default_config:
history:
logbook:
zeroconf:
network:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.openflame: debug
    homeassistant.components.bluetooth: debug
    homeassistant.components.zeroconf: debug
    homeassistant.components.network: debug

automation: !include automations.yaml


shell_command:
  cmd_flames_on: 'curl "http://magikflamedemo.t3chkommie.com/flameson"'
  cmd_flames_off: 'curl "http://magikflamedemo.t3chkommie.com/flamesoff"'
